[package]
name = "rwa-nft"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.32.1"
anchor-spl = "0.32.1"
spl-token = { version = "6", features = ["no-entrypoint"] }
